Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt : .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png

Database :
  DBType: mysql
  Username: root
  Password: aaaa
  Host: 127.0.0.1:3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30


JWT:
  Secret: whitestorm
  Issuer: blog-service
  Expire: 7200

Email:
  Host: smtp.qq.com
  Port: 465
  UserName: 506517609@qq.com
  Password: 506517609nima
  IsSSL: true
  From: 506517609@qq.com
  To: 
    - 506517609@qq.com
  